apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: todo-app
build:
  artifacts:
  - image: todo-backend
    context: .
    docker:
      dockerfile: backend/Dockerfile
    sync:
      manual:
      - src: "backend/**/*.go"
        dest: .
  - image: todo-frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.js"
        dest: .
      - src: "**/*.jsx"
        dest: .
      - src: "**/*.ts"
        dest: .
      - src: "**/*.tsx"
        dest: .
manifests:
  rawYaml:
  # Base resources
  - k8s/base/namespace.yaml
  
  # Application resources
  - k8s/app/backend-deployment.yaml
  - k8s/app/backend-service.yaml
  - k8s/app/frontend-deployment.yaml
  - k8s/app/frontend-service.yaml
  
  # Database resources
  - k8s/database/mariadb-root-secret.yaml
  - k8s/database/mariadb-secret.yaml
  - k8s/database/mariadb-instance.yaml
  - k8s/database/mariadb-database.yaml
  - k8s/database/mariadb-user.yaml
  - k8s/database/mariadb-grant.yaml
deploy:
  helm:
    releases:
    - name: mariadb-operator
      remoteChart: mariadb-operator
      repo: https://mariadb-operator.github.io/mariadb-operator
      version: 0.38.1
      namespace: mariadb-system
      createNamespace: true
      setValues:
        logLevel: INFO
        ha.enabled: false
        metrics.enabled: false
        webhook.enabled: true
        webhook.cert.certManager.enabled: false
  kubectl: {}
profiles:
- name: dev
  build:
    local:
      push: false
      useBuildkit: true
    tagPolicy:
      gitCommit: {}
  deploy:
    kubectl:
      flags:
        global: ["--context=orbstack"]
  portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 3000
  - resourceType: service
    resourceName: backend-service
    port: 8080
- name: production
  build:
    cluster: {}
  deploy:
    kubectl: {}