# Kustomization for development environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: todo-app-development

# Namespace for all resources
namespace: todo-app

# Resources to include
resources:
- namespace.yaml
- backend-configmap.yaml
- frontend-configmap.yaml
- secrets.yaml
- mysql-simple.yaml
- mysql-init.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
- network-policy.yaml

# Common labels for all resources
commonLabels:
  environment: development
  version: v1.0.0
  managed-by: kustomize

# Common annotations
commonAnnotations:
  documentation: "https://github.com/wcygan/todo"
  contact: "dev-team@company.com"

# Images to use (override for different environments)
images:
- name: todo-backend
  newTag: latest
- name: todo-frontend
  newTag: latest

# Patches for development environment
patches:
# Reduce resource limits for minikube
- target:
    kind: Deployment
    name: backend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "200m"

- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "300m"

# Enable debug logging for development
- target:
    kind: ConfigMap
    name: backend-config
  patch: |-
    - op: replace
      path: /data/development.json
      value: |
        {
          "server": {
            "port": 8080,
            "read_timeout": "30s",
            "write_timeout": "30s",
            "idle_timeout": "60s",
            "shutdown_timeout": "15s",
            "cors": {
              "allowed_origins": ["*"],
              "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
              "allowed_headers": ["Content-Type", "Connect-Protocol-Version", "Connect-Timeout-Ms"]
            }
          },
          "logger": {
            "level": "debug",
            "format": "text"
          },
          "database": {
            "host": "mysql-service",
            "port": 3306,
            "name": "todoapp",
            "max_open_conns": 10,
            "max_idle_conns": 5,
            "conn_max_lifetime": "5m"
          }
        }