# MySQL Operator InnoDBCluster for development
# This assumes MySQL Operator for Kubernetes is installed
# Install with: kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-crds.yaml
#               kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-operator.yaml

apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: todo-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    environment: development
spec:
  # Single instance for development - scale to 3 for production
  instances: 1
  
  # MySQL version - using latest stable
  version: "9.0.1"
  
  # Root password from secret
  secretName: mysql-credentials
  
  # TLS configuration
  tlsUseSelfSigned: true
  
  # Development-friendly resource limits
  podSpec:
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    
    # Fast storage for development
    terminationGracePeriodSeconds: 30
  
  # Data directory and storage
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    # For production, use faster storage class:
    # storageClassName: fast-ssd
  
  # Router configuration for load balancing
  router:
    instances: 0  # Disable router for development simplicity

