# Database initialization job
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
  namespace: todo-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: init
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mysql-init
        image: mysql:8.0.35
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: database
        command:
        - /bin/bash
        - -c
        - |
          # Wait for MySQL to be ready
          until mysql -h mysql-cluster-instances -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          
          # Create database if it doesn't exist
          mysql -h mysql-cluster-instances -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
          
          # Create tables for todo application
          mysql -h mysql-cluster-instances -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE <<EOF
          CREATE TABLE IF NOT EXISTS tasks (
            id VARCHAR(36) PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            is_completed BOOLEAN DEFAULT FALSE,
            priority ENUM('none', 'low', 'medium', 'high') DEFAULT 'none',
            due_date DATETIME NULL,
            notes TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            completed_at DATETIME NULL,
            INDEX idx_is_completed (is_completed),
            INDEX idx_priority (priority),
            INDEX idx_due_date (due_date),
            INDEX idx_created_at (created_at)
          );
          EOF
          
          echo "Database initialization completed"
      
      # Wait for MySQL cluster to be ready
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          until nc -z mysql-cluster-instances 3306; do
            echo "Waiting for MySQL cluster..."
            sleep 5
          done
          echo "MySQL cluster is ready"