apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: todo-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
type: Opaque
data:
  # Base64 encoded credentials
  # Username: todouser (dG9kb3VzZXI=)
  # Password: tododev123 (dG9kb2RldjEyMw==)
  # Database: todoapp (dG9kb2FwcA==)
  username: dG9kb3VzZXI=
  password: dG9kb2RldjEyMw==
  rootPassword: dG9kb2RldjEyMw==
  database: dG9kb2FwcA==

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-backend
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Database connection string
  # mysql://todouser:tododev123@mysql-service:3306/todoapp
  database-url: bXlzcWw6Ly90b2RvdXNlcjp0b2RvZGV2MTIzQG15c3FsLXNlcnZpY2U6MzMwNi90b2RvYXBw