# Tilt configuration for development workflow
# This file is used by Tilt to provide hot reload and development features

apiVersion: v1
kind: ConfigMap
metadata:
  name: tilt-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: tilt
    app.kubernetes.io/component: development
data:
  # Tilt development settings
  tilt-settings.yaml: |
    # Development mode settings
    development:
      hot_reload: true
      live_update: true
      auto_rebuild: true
      
    # Resource management
    resources:
      backend:
        dockerfile: k8s/backend/Dockerfile
        context: backend/
        live_update:
          - sync: backend/
            exclude: ['*_test.go', '*.md']
        auto_init: true
        
      frontend:
        dockerfile: k8s/frontend/Dockerfile
        context: frontend/
        live_update:
          - sync: frontend/src/
            target: /app/src/
          - sync: frontend/package.json
            target: /app/package.json
        auto_init: true
    
    # Port forwarding for local development
    port_forwards:
      - resource: frontend-service
        local_port: 3000
        container_port: 3000
      - resource: backend-service
        local_port: 8080
        container_port: 8080
      - resource: mysql-cluster-mysql-master
        local_port: 3306
        container_port: 3306
    
    # Watch settings
    watch_settings:
      ignore:
        - '**/.git/**'
        - '**/node_modules/**'
        - '**/vendor/**'
        - '**/*.log'
        - '**/tmp/**'
        - '**/.next/**'
    
    # Build optimization
    build:
      disable_optimizations: true
      disable_push: true