apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend-dev
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: backend-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: backend-dev
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: todo-app
    spec:
      initContainers:
      - name: wait-for-mariadb
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for MariaDB to be ready..."
          until nc -z todo-mariadb.todo-app.svc.cluster.local 3306; do
            echo "MariaDB is not ready yet. Waiting 5 seconds..."
            sleep 5
          done
          echo "MariaDB is ready!"
      containers:
      - name: backend
        image: todo-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: TODO_ENV
          value: "development"
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "todo-mariadb.todo-app.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "todoapp"
        - name: DB_PASSWORD
          value: "todouser123"
        - name: DB_NAME
          value: "todoapp"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL