apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend-dev
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend-dev