name: Buf Push

on:
  push:
    branches: [main]
    paths:
      - 'proto/**'

jobs:
  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Buf
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
      - name: Push to Buf Schema Registry
        run: |
          cd proto
          buf push